### ISSUE TITLE
File name does not match module name

### ISSUE THREAD

**Issue by klememi** [MI-AFP/hw03#2]
`stack build` failed because of the wrong module name on the 1st line in `src/Data/MyString/Examples.hs`. After changing `module Examples where` to `module Data.MyString.Examples where` everything worked fine.

**Comment by klememi** [comment]
I'm confused, maybe it's intended? (as a part of homework) 😇

**Comment by MarekSuchanek** [comment]
:smile: It is definitely a good extra practice with modules!

**Comment by tillydray** [comment]
Can this issue be closed? Lots of people will be looking for good first issues during October (because of Hacktoberfest) and this issue will likely be visited frequently.

**Comment by MarekSuchanek** [comment]
Fixed in https://github.com/MI-AFP/hw03/commit/bc6dc71336f571571ccb3021b28b092496e2473c
